version: '3.8'

services:
  # 1. MINIO (Data Lake Storage)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin} # Fallback nếu .env thiếu
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - lake-net

  # 2. JUPYTER SPARK (Processing Engine)
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    volumes:
      # Mount toàn bộ thư mục dự án vào /home/jovyan/work để tiện truy cập
      - ./:/home/jovyan/work
      # Mount thư mục JARs vào đường dẫn riêng để dễ config
      - ./jars:/home/jovyan/jars
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - lake-net

  # 3. REDIS (Serving Layer / Feature Store)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      # Lưu dữ liệu Redis xuống ổ cứng để không mất khi restart
      - redis_data:/data
    networks:
      - lake-net

  # 4. API (Serving Interface)
  api:
    build: ./api_service
    container_name: spotify-api # Đặt tên rõ ràng
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - lake-net

  # 5. KAFKA & ZOOKEEPER (Streaming Infrastructure)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - lake-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Port cho Producer chạy trên Windows
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình Dual Listeners:
      # - INSIDE: Cho Spark trong Docker (dùng kafka:29092)
      # - OUTSIDE: Cho Python trên Windows (dùng localhost:9092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - lake-net

# 6. VOLUMES & NETWORKS
volumes:
  minio_data:
  redis_data: # Thêm volume cho Redis

networks:
  lake-net:
    driver: bridge