version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # UI port
    volumes:
      - ./minio_data:/data
    environment:
      # Value of.env
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - lake-net
  
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    volumes:
      - ./:/home/jovyan/work
      # üëá D√íNG QUAN TR·ªåNG NH·∫§T:
      # B√™n tr√°i d·∫•u : l√† folder tr√™n m√°y b·∫°n (D:\spotify_trends\notebooks)
      # B√™n ph·∫£i d·∫•u : l√† folder trong Docker (/home/jovyan/work)
      - ./notebooks:/home/jovyan/work

      # Mount JARs ƒë·ªÉ d√πng (nh∆∞ c≈©)
      - ./jars:/home/jovyan/jars
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - lake-net
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - lake-net

  # üëá TH√äM SERVICE API V√ÄO ƒê√ÇY
  api:
    build: ./api_service  # Build t·ª´ folder api_service
    container_name: spotify-api
    ports:
      - "8000:8000"       # M·ªü c·ªïng 8000 ra m√°y th·∫≠t
    environment:
      - REDIS_HOST=redis  # T√™n service c·ªßa container Redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - lake-net          # C√πng m·∫°ng v·ªõi Redis

networks:
  lake-net: