version: '3.8'

services:
  # 1. MinIO (Kho chá»©a dá»¯ liá»‡u)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      # Dá»¯ liá»‡u há»‡ thá»‘ng MinIO
      - ./minio_data:/data
      # Mount folder JSON cá»§a báº¡n (Ä‘Ã£ náº±m trong minio_data nhÆ°ng mount riÃªng cho cháº¯c)
    command: server /data --console-address ":9001"
    networks:
      - lake-net

  # 2. Jupyter Notebook (NÆ¡i báº¡n lÃ m viá»‡c)
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    volumes:
      # ðŸ‘‡ DÃ’NG QUAN TRá»ŒNG NHáº¤T:
      # BÃªn trÃ¡i dáº¥u : lÃ  folder trÃªn mÃ¡y báº¡n (D:\spotify_trends\notebooks)
      # BÃªn pháº£i dáº¥u : lÃ  folder trong Docker (/home/jovyan/work)
      - ./notebooks:/home/jovyan/work
      
      # Mount JARs Ä‘á»ƒ dÃ¹ng (nhÆ° cÅ©)
      - ./jars:/home/jovyan/jars
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - lake-net

networks:
  lake-net: