apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spotify

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spotify
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spotify
subjects:
- kind: ServiceAccount
  name: spark
  namespace: spotify
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io