apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spotify
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spotify
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "events", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "delete", "deletecollection", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-binding
  namespace: spotify
subjects:
- kind: ServiceAccount
  name: spark
  namespace: spotify
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io