apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: spotify
spec:
  selector:
    app: spotify-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002
  type: NodePort
